CATALOG = [
    {
        "id": "choco_01",
        "name": "Dark 70% Cacao",
        "brand": "Lindt",
        "price": 2.49,
        "old_price": 3.29,
        "discount_percent": 24,
        "rating": 4.7,
        "reviews_count": 1280,
        "image": "/images/choco_01.jpg",
        "trusted": True,
    },
    {
        "id": "choco_02",
        "name": "Milk Chocolate Classic",
        "brand": "Milka",
        "price": 1.79,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.4,
        "reviews_count": 940,
        "image": "/images/choco_02.jpg",
        "trusted": True,
    },
    {
        "id": "choco_03",
        "name": "Hazelnut Praline",
        "brand": "Ritter Sport",
        "price": 2.19,
        "old_price": 2.89,
        "discount_percent": 24,
        "rating": 4.6,
        "reviews_count": 610,
        "image": "/images/choco_03.jpg",
        "trusted": True,
    },
    {
        "id": "choco_04",
        "name": "Sea Salt Caramel",
        "brand": "Rimi Selection",
        "price": 1.49,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.1,
        "reviews_count": 210,
        "image": "/images/choco_04.jpg",
        "trusted": False,
    },
    {
        "id": "choco_05",
        "name": "White Chocolate Vanilla",
        "brand": "Milka",
        "price": 1.99,
        "old_price": 2.49,
        "discount_percent": 20,
        "rating": 4.2,
        "reviews_count": 350,
        "image": "/images/choco_05.jpg",
        "trusted": True,
    },
    {
        "id": "choco_06",
        "name": "Dark Orange 60%",
        "brand": "Fazer",
        "price": 2.59,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.5,
        "reviews_count": 480,
        "image": "/images/choco_06.jpg",
        "trusted": True,
    },
    {
        "id": "choco_07",
        "name": "Almond Crunch",
        "brand": "Maxima Basic",
        "price": 0.99,
        "old_price": 1.59,
        "discount_percent": 38,
        "rating": 3.9,
        "reviews_count": 120,
        "image": "/images/choco_07.jpg",
        "trusted": False,
    },
    {
        "id": "choco_08",
        "name": "Ruby Berry",
        "brand": "Lindt",
        "price": 3.19,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.8,
        "reviews_count": 760,
        "image": "/images/choco_08.jpg",
        "trusted": True,
    },
    {
        "id": "choco_09",
        "name": "Coconut Milk Bar",
        "brand": "Rimi Selection",
        "price": 1.29,
        "old_price": 1.79,
        "discount_percent": 28,
        "rating": 4.0,
        "reviews_count": 95,
        "image": "/images/choco_09.jpg",
        "trusted": False,
    },
    {
        "id": "choco_10",
        "name": "Extra Dark 85%",
        "brand": "Ritter Sport",
        "price": 2.29,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.3,
        "reviews_count": 540,
        "image": "/images/choco_10.jpg",
        "trusted": True,
    },
]

CATALOG_BY_ID = {p["id"]: p for p in CATALOG}


def get_catalog():
    return CATALOG


def product_name(product_id):
    p = CATALOG_BY_ID.get(product_id)
    return p["name"] if p else product_id
