CATALOG = [
    {
        "id": "choco_01",
        "name": "Milk Chocolate",
        "brand": "Velora",
        "price": 2.19,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.5,
        "reviews_count": 860,
        "image": "/images/choco_01.jpg",
        "trusted": True,
    },
    {
        "id": "choco_02",
        "name": "Hazelnut Crunch",
        "brand": "Nuvola",
        "price": 1.99,
        "old_price": 2.59,
        "discount_percent": 23,
        "rating": 4.4,
        "reviews_count": 610,
        "image": "/images/choco_02.jpg",
        "trusted": True,
    },
    {
        "id": "choco_03",
        "name": "Dark Chocolate 70%",
        "brand": "Nocturra",
        "price": 2.79,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.7,
        "reviews_count": 1180,
        "image": "/images/choco_03.jpg",
        "trusted": True,
    },
    {
        "id": "choco_04",
        "name": "Strawberry & Cream",
        "brand": "Elysia",
        "price": 1.49,
        "old_price": 1.99,
        "discount_percent": 25,
        "rating": 4.1,
        "reviews_count": 240,
        "image": "/images/choco_04.jpg",
        "trusted": False,
    },
    {
        "id": "choco_05",
        "name": "Pistachio & Sea Salt",
        "brand": "Veridan",
        "price": 2.99,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.6,
        "reviews_count": 520,
        "image": "/images/choco_05.jpg",
        "trusted": True,
    },
    {
        "id": "choco_06",
        "name": "Raspberry Dark",
        "brand": "Aurelli",
        "price": 2.29,
        "old_price": 2.89,
        "discount_percent": 21,
        "rating": 4.5,
        "reviews_count": 430,
        "image": "/images/choco_06.jpg",
        "trusted": True,
    },
    {
        "id": "choco_07",
        "name": "Coffee Crisp",
        "brand": "Kalias",
        "price": 0.99,
        "old_price": 1.59,
        "discount_percent": 38,
        "rating": 3.9,
        "reviews_count": 130,
        "image": "/images/choco_07.jpg",
        "trusted": False,
    },
    {
        "id": "choco_08",
        "name": "Mint Dark Chocolate",
        "brand": "Lunora",
        "price": 2.09,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.3,
        "reviews_count": 470,
        "image": "/images/choco_08.jpg",
        "trusted": True,
    },
    {
        "id": "choco_09",
        "name": "Extra Dark 85%",
        "brand": "Maretti",
        "price": 3.19,
        "old_price": None,
        "discount_percent": 0,
        "rating": 4.8,
        "reviews_count": 760,
        "image": "/images/choco_09.jpg",
        "trusted": True,
    },
    {
        "id": "choco_10",
        "name": "Caramel & Almond",
        "brand": "Sollen",
        "price": 1.29,
        "old_price": 1.79,
        "discount_percent": 28,
        "rating": 4.0,
        "reviews_count": 150,
        "image": "/images/choco_10.jpg",
        "trusted": False,
    },
]

CATALOG_BY_ID = {p["id"]: p for p in CATALOG}


def get_catalog():
    return CATALOG


def product_name(product_id):
    p = CATALOG_BY_ID.get(product_id)
    return p["name"] if p else product_id
